# Generated by Django 3.1.5 on 2021-03-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'todo_list',
            },
        ),
    ]
